// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.1 (commit 3d7607082ab47257adeb7c25164536511237f2b5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import CancelFindMatchReducer from "./cancel_find_match_reducer";
import ChooseColonyReducer from "./choose_colony_reducer";
import ClaimAdminReducer from "./claim_admin_reducer";
import ConfirmMatchReducer from "./confirm_match_reducer";
import CreatePartyReducer from "./create_party_reducer";
import DeclineMatchReducer from "./decline_match_reducer";
import DiscoverLocationReducer from "./discover_location_reducer";
import DiscoverPlanetReducer from "./discover_planet_reducer";
import EquipItemReducer from "./equip_item_reducer";
import FindMatchReducer from "./find_match_reducer";
import FindRankedMatchReducer from "./find_ranked_match_reducer";
import FollowPlayerReducer from "./follow_player_reducer";
import GrantCurrencyAdminReducer from "./grant_currency_admin_reducer";
import GrantItemAdminReducer from "./grant_item_admin_reducer";
import JoinMatchReducer from "./join_match_reducer";
import JoinPartyReducer from "./join_party_reducer";
import JoinPartyByCodeReducer from "./join_party_by_code_reducer";
import KickFromPartyReducer from "./kick_from_party_reducer";
import LeaveMatchReducer from "./leave_match_reducer";
import LeavePartyReducer from "./leave_party_reducer";
import RecordProfileViewReducer from "./record_profile_view_reducer";
import ReportMatchStatsReducer from "./report_match_stats_reducer";
import ReportNecrophageVictoryReducer from "./report_necrophage_victory_reducer";
import ReportNexusCaptureReducer from "./report_nexus_capture_reducer";
import SendMatchMsgReducer from "./send_match_msg_reducer";
import SetAvatarReducer from "./set_avatar_reducer";
import SetBanAdminReducer from "./set_ban_admin_reducer";
import SetBioReducer from "./set_bio_reducer";
import SetGenderReducer from "./set_gender_reducer";
import SetKeybindsReducer from "./set_keybinds_reducer";
import SetPartyLoadoutReducer from "./set_party_loadout_reducer";
import SetPlayerNameReducer from "./set_player_name_reducer";
import SetProfileNameReducer from "./set_profile_name_reducer";
import SetProfilePictureReducer from "./set_profile_picture_reducer";
import SubmitInputReducer from "./submit_input_reducer";
import SubmitPeerResultReducer from "./submit_peer_result_reducer";
import SyncPoseReducer from "./sync_pose_reducer";
import UnfollowPlayerReducer from "./unfollow_player_reducer";

// Import all procedure arg schemas
import * as ColonyStatsProcedure from "./colony_stats_procedure";
import * as SearchPlayersProcedure from "./search_players_procedure";

// Import all table schema definitions
import FollowRow from "./follow_table";
import MatchRow from "./match_table";
import MatchEntityRow from "./match_entity_table";
import MatchEventRow from "./match_event_table";
import MatchHistoryRow from "./match_history_table";
import MatchMsgRow from "./match_msg_table";
import MatchObjectiveRow from "./match_objective_table";
import MatchPlayerRow from "./match_player_table";
import MyCandidateRow from "./my_candidate_table";
import MyCandidatePlayersRow from "./my_candidate_players_table";
import MyMatchUsageRow from "./my_match_usage_table";
import MyQueueEntryRow from "./my_queue_entry_table";
import PartyRow from "./party_table";
import PartyMemberRow from "./party_member_table";
import PlanetControlHistoryRow from "./planet_control_history_table";
import PlanetDiscoveryRow from "./planet_discovery_table";
import PlayerRow from "./player_table";
import PlayerInventoryRow from "./player_inventory_table";
import PlayerLoadoutRow from "./player_loadout_table";
import PlayerPresenceRow from "./player_presence_table";
import PlayerSettingsRow from "./player_settings_table";
import PlayerStatsRow from "./player_stats_table";
import PlayerWalletRow from "./player_wallet_table";
import ProfileViewRow from "./profile_view_table";
import RankHistoryRow from "./rank_history_table";
import RankedLocationDiscoveryRow from "./ranked_location_discovery_table";
import RankedPlanetRow from "./ranked_planet_table";
import RankedPlanetReservationRow from "./ranked_planet_reservation_table";
import RankedSeasonRow from "./ranked_season_table";
import RankedTopRow from "./ranked_top_table";
import ServerClockRow from "./server_clock_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  follow: __table({
    name: 'follow',
    indexes: [
      { accessor: 'follower', name: 'follow_follower_idx_btree', algorithm: 'btree', columns: [
        'follower',
      ] },
      { accessor: 'following', name: 'follow_following_idx_btree', algorithm: 'btree', columns: [
        'following',
      ] },
      { accessor: 'id', name: 'follow_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'follow_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FollowRow),
  match: __table({
    name: 'match',
    indexes: [
      { accessor: 'match_id', name: 'match_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
      { name: 'match_match_id_key', constraint: 'unique', columns: ['matchId'] },
    ],
  }, MatchRow),
  matchEntity: __table({
    name: 'match_entity',
    indexes: [
      { accessor: 'id', name: 'match_entity_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'match_id', name: 'match_entity_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
      { name: 'match_entity_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchEntityRow),
  matchEvent: __table({
    name: 'match_event',
    indexes: [
      { accessor: 'id', name: 'match_event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'match_id', name: 'match_event_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
      { name: 'match_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchEventRow),
  matchHistory: __table({
    name: 'match_history',
    indexes: [
      { accessor: 'id', name: 'match_history_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'match_history_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'match_history_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchHistoryRow),
  matchMsg: __table({
    name: 'match_msg',
    indexes: [
      { accessor: 'id', name: 'match_msg_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'match_id', name: 'match_msg_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
      { name: 'match_msg_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchMsgRow),
  matchObjective: __table({
    name: 'match_objective',
    indexes: [
      { accessor: 'id', name: 'match_objective_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'match_id', name: 'match_objective_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
      { name: 'match_objective_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchObjectiveRow),
  matchPlayer: __table({
    name: 'match_player',
    indexes: [
      { accessor: 'id', name: 'match_player_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'match_player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'match_id', name: 'match_player_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
      { name: 'match_player_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchPlayerRow),
  party: __table({
    name: 'party',
    indexes: [
      { accessor: 'party_id', name: 'party_party_id_idx_btree', algorithm: 'btree', columns: [
        'partyId',
      ] },
    ],
    constraints: [
      { name: 'party_party_id_key', constraint: 'unique', columns: ['partyId'] },
    ],
  }, PartyRow),
  partyMember: __table({
    name: 'party_member',
    indexes: [
      { accessor: 'id', name: 'party_member_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'party_member_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'party_id', name: 'party_member_party_id_idx_btree', algorithm: 'btree', columns: [
        'partyId',
      ] },
    ],
    constraints: [
      { name: 'party_member_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'party_member_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PartyMemberRow),
  planetControlHistory: __table({
    name: 'planet_control_history',
    indexes: [
      { accessor: 'id', name: 'planet_control_history_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'planet_key', name: 'planet_control_history_planet_key_idx_btree', algorithm: 'btree', columns: [
        'planetKey',
      ] },
    ],
    constraints: [
      { name: 'planet_control_history_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlanetControlHistoryRow),
  planetDiscovery: __table({
    name: 'planet_discovery',
    indexes: [
      { accessor: 'id', name: 'planet_discovery_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'planet_key', name: 'planet_discovery_planet_key_idx_btree', algorithm: 'btree', columns: [
        'planetKey',
      ] },
    ],
    constraints: [
      { name: 'planet_discovery_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlanetDiscoveryRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'normalized_name', name: 'player_normalized_name_idx_btree', algorithm: 'btree', columns: [
        'normalizedName',
      ] },
      { accessor: 'player_code', name: 'player_player_code_idx_btree', algorithm: 'btree', columns: [
        'playerCode',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
      { name: 'player_normalized_name_key', constraint: 'unique', columns: ['normalizedName'] },
    ],
  }, PlayerRow),
  playerInventory: __table({
    name: 'player_inventory',
    indexes: [
      { accessor: 'id', name: 'player_inventory_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'player_inventory_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_inventory_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayerInventoryRow),
  playerLoadout: __table({
    name: 'player_loadout',
    indexes: [
      { accessor: 'id', name: 'player_loadout_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'player_loadout_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_loadout_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayerLoadoutRow),
  playerPresence: __table({
    name: 'player_presence',
    indexes: [
      { accessor: 'identity', name: 'player_presence_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_presence_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerPresenceRow),
  playerSettings: __table({
    name: 'player_settings',
    indexes: [
      { accessor: 'identity', name: 'player_settings_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_settings_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerSettingsRow),
  playerStats: __table({
    name: 'player_stats',
    indexes: [
      { accessor: 'identity', name: 'player_stats_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_stats_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerStatsRow),
  playerWallet: __table({
    name: 'player_wallet',
    indexes: [
      { accessor: 'identity', name: 'player_wallet_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_wallet_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerWalletRow),
  profileView: __table({
    name: 'profile_view',
    indexes: [
      { accessor: 'id', name: 'profile_view_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'profile', name: 'profile_view_profile_idx_btree', algorithm: 'btree', columns: [
        'profile',
      ] },
      { accessor: 'viewer', name: 'profile_view_viewer_idx_btree', algorithm: 'btree', columns: [
        'viewer',
      ] },
    ],
    constraints: [
      { name: 'profile_view_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProfileViewRow),
  rankHistory: __table({
    name: 'rank_history',
    indexes: [
      { accessor: 'id', name: 'rank_history_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'rank_history_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'rank_history_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RankHistoryRow),
  rankedLocationDiscovery: __table({
    name: 'ranked_location_discovery',
    indexes: [
      { accessor: 'galaxy_id', name: 'ranked_location_discovery_galaxy_id_idx_btree', algorithm: 'btree', columns: [
        'galaxyId',
      ] },
      { accessor: 'id', name: 'ranked_location_discovery_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'location_key', name: 'ranked_location_discovery_location_key_idx_btree', algorithm: 'btree', columns: [
        'locationKey',
      ] },
      { accessor: 'player_identity', name: 'ranked_location_discovery_player_identity_idx_btree', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'ranked_location_discovery_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RankedLocationDiscoveryRow),
  rankedPlanet: __table({
    name: 'ranked_planet',
    indexes: [
      { accessor: 'galaxy_id', name: 'ranked_planet_galaxy_id_idx_btree', algorithm: 'btree', columns: [
        'galaxyId',
      ] },
      { accessor: 'planet_key', name: 'ranked_planet_planet_key_idx_btree', algorithm: 'btree', columns: [
        'planetKey',
      ] },
    ],
    constraints: [
      { name: 'ranked_planet_planet_key_key', constraint: 'unique', columns: ['planetKey'] },
    ],
  }, RankedPlanetRow),
  rankedPlanetReservation: __table({
    name: 'ranked_planet_reservation',
    indexes: [
      { accessor: 'planet_key', name: 'ranked_planet_reservation_planet_key_idx_btree', algorithm: 'btree', columns: [
        'planetKey',
      ] },
    ],
    constraints: [
      { name: 'ranked_planet_reservation_planet_key_key', constraint: 'unique', columns: ['planetKey'] },
    ],
  }, RankedPlanetReservationRow),
  rankedSeason: __table({
    name: 'ranked_season',
    indexes: [
      { accessor: 'season_id', name: 'ranked_season_season_id_idx_btree', algorithm: 'btree', columns: [
        'seasonId',
      ] },
    ],
    constraints: [
      { name: 'ranked_season_season_id_key', constraint: 'unique', columns: ['seasonId'] },
    ],
  }, RankedSeasonRow),
  serverClock: __table({
    name: 'server_clock',
    indexes: [
      { accessor: 'id', name: 'server_clock_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'server_clock_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ServerClockRow),
  myCandidate: __table({
    name: 'my_candidate',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCandidateRow),
  myCandidatePlayers: __table({
    name: 'my_candidate_players',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCandidatePlayersRow),
  myMatchUsage: __table({
    name: 'my_match_usage',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMatchUsageRow),
  myQueueEntry: __table({
    name: 'my_queue_entry',
    indexes: [
    ],
    constraints: [
    ],
  }, MyQueueEntryRow),
  rankedTop: __table({
    name: 'ranked_top',
    indexes: [
    ],
    constraints: [
    ],
  }, RankedTopRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("cancel_find_match", CancelFindMatchReducer),
  __reducerSchema("choose_colony", ChooseColonyReducer),
  __reducerSchema("claim_admin", ClaimAdminReducer),
  __reducerSchema("confirm_match", ConfirmMatchReducer),
  __reducerSchema("create_party", CreatePartyReducer),
  __reducerSchema("decline_match", DeclineMatchReducer),
  __reducerSchema("discover_location", DiscoverLocationReducer),
  __reducerSchema("discover_planet", DiscoverPlanetReducer),
  __reducerSchema("equip_item", EquipItemReducer),
  __reducerSchema("find_match", FindMatchReducer),
  __reducerSchema("find_ranked_match", FindRankedMatchReducer),
  __reducerSchema("follow_player", FollowPlayerReducer),
  __reducerSchema("grant_currency_admin", GrantCurrencyAdminReducer),
  __reducerSchema("grant_item_admin", GrantItemAdminReducer),
  __reducerSchema("join_match", JoinMatchReducer),
  __reducerSchema("join_party", JoinPartyReducer),
  __reducerSchema("join_party_by_code", JoinPartyByCodeReducer),
  __reducerSchema("kick_from_party", KickFromPartyReducer),
  __reducerSchema("leave_match", LeaveMatchReducer),
  __reducerSchema("leave_party", LeavePartyReducer),
  __reducerSchema("record_profile_view", RecordProfileViewReducer),
  __reducerSchema("report_match_stats", ReportMatchStatsReducer),
  __reducerSchema("report_necrophage_victory", ReportNecrophageVictoryReducer),
  __reducerSchema("report_nexus_capture", ReportNexusCaptureReducer),
  __reducerSchema("send_match_msg", SendMatchMsgReducer),
  __reducerSchema("set_avatar", SetAvatarReducer),
  __reducerSchema("set_ban_admin", SetBanAdminReducer),
  __reducerSchema("set_bio", SetBioReducer),
  __reducerSchema("set_gender", SetGenderReducer),
  __reducerSchema("set_keybinds", SetKeybindsReducer),
  __reducerSchema("set_party_loadout", SetPartyLoadoutReducer),
  __reducerSchema("set_player_name", SetPlayerNameReducer),
  __reducerSchema("set_profile_name", SetProfileNameReducer),
  __reducerSchema("set_profile_picture", SetProfilePictureReducer),
  __reducerSchema("submit_input", SubmitInputReducer),
  __reducerSchema("submit_peer_result", SubmitPeerResultReducer),
  __reducerSchema("sync_pose", SyncPoseReducer),
  __reducerSchema("unfollow_player", UnfollowPlayerReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("colony_stats", ColonyStatsProcedure.params, ColonyStatsProcedure.returnType),
  __procedureSchema("search_players", SearchPlayersProcedure.params, SearchPlayersProcedure.returnType),
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `matchEntity` instead. This alias will be removed in the next major version. */
    readonly "match_entity": Omit<typeof tablesSchema.schemaType.tables["matchEntity"], "accessorName"> & { readonly accessorName: "match_entity" };
    /** @deprecated Use `matchEvent` instead. This alias will be removed in the next major version. */
    readonly "match_event": Omit<typeof tablesSchema.schemaType.tables["matchEvent"], "accessorName"> & { readonly accessorName: "match_event" };
    /** @deprecated Use `matchHistory` instead. This alias will be removed in the next major version. */
    readonly "match_history": Omit<typeof tablesSchema.schemaType.tables["matchHistory"], "accessorName"> & { readonly accessorName: "match_history" };
    /** @deprecated Use `matchMsg` instead. This alias will be removed in the next major version. */
    readonly "match_msg": Omit<typeof tablesSchema.schemaType.tables["matchMsg"], "accessorName"> & { readonly accessorName: "match_msg" };
    /** @deprecated Use `matchObjective` instead. This alias will be removed in the next major version. */
    readonly "match_objective": Omit<typeof tablesSchema.schemaType.tables["matchObjective"], "accessorName"> & { readonly accessorName: "match_objective" };
    /** @deprecated Use `matchPlayer` instead. This alias will be removed in the next major version. */
    readonly "match_player": Omit<typeof tablesSchema.schemaType.tables["matchPlayer"], "accessorName"> & { readonly accessorName: "match_player" };
    /** @deprecated Use `partyMember` instead. This alias will be removed in the next major version. */
    readonly "party_member": Omit<typeof tablesSchema.schemaType.tables["partyMember"], "accessorName"> & { readonly accessorName: "party_member" };
    /** @deprecated Use `planetControlHistory` instead. This alias will be removed in the next major version. */
    readonly "planet_control_history": Omit<typeof tablesSchema.schemaType.tables["planetControlHistory"], "accessorName"> & { readonly accessorName: "planet_control_history" };
    /** @deprecated Use `planetDiscovery` instead. This alias will be removed in the next major version. */
    readonly "planet_discovery": Omit<typeof tablesSchema.schemaType.tables["planetDiscovery"], "accessorName"> & { readonly accessorName: "planet_discovery" };
    /** @deprecated Use `playerInventory` instead. This alias will be removed in the next major version. */
    readonly "player_inventory": Omit<typeof tablesSchema.schemaType.tables["playerInventory"], "accessorName"> & { readonly accessorName: "player_inventory" };
    /** @deprecated Use `playerLoadout` instead. This alias will be removed in the next major version. */
    readonly "player_loadout": Omit<typeof tablesSchema.schemaType.tables["playerLoadout"], "accessorName"> & { readonly accessorName: "player_loadout" };
    /** @deprecated Use `playerPresence` instead. This alias will be removed in the next major version. */
    readonly "player_presence": Omit<typeof tablesSchema.schemaType.tables["playerPresence"], "accessorName"> & { readonly accessorName: "player_presence" };
    /** @deprecated Use `playerSettings` instead. This alias will be removed in the next major version. */
    readonly "player_settings": Omit<typeof tablesSchema.schemaType.tables["playerSettings"], "accessorName"> & { readonly accessorName: "player_settings" };
    /** @deprecated Use `playerStats` instead. This alias will be removed in the next major version. */
    readonly "player_stats": Omit<typeof tablesSchema.schemaType.tables["playerStats"], "accessorName"> & { readonly accessorName: "player_stats" };
    /** @deprecated Use `playerWallet` instead. This alias will be removed in the next major version. */
    readonly "player_wallet": Omit<typeof tablesSchema.schemaType.tables["playerWallet"], "accessorName"> & { readonly accessorName: "player_wallet" };
    /** @deprecated Use `profileView` instead. This alias will be removed in the next major version. */
    readonly "profile_view": Omit<typeof tablesSchema.schemaType.tables["profileView"], "accessorName"> & { readonly accessorName: "profile_view" };
    /** @deprecated Use `rankHistory` instead. This alias will be removed in the next major version. */
    readonly "rank_history": Omit<typeof tablesSchema.schemaType.tables["rankHistory"], "accessorName"> & { readonly accessorName: "rank_history" };
    /** @deprecated Use `rankedLocationDiscovery` instead. This alias will be removed in the next major version. */
    readonly "ranked_location_discovery": Omit<typeof tablesSchema.schemaType.tables["rankedLocationDiscovery"], "accessorName"> & { readonly accessorName: "ranked_location_discovery" };
    /** @deprecated Use `rankedPlanet` instead. This alias will be removed in the next major version. */
    readonly "ranked_planet": Omit<typeof tablesSchema.schemaType.tables["rankedPlanet"], "accessorName"> & { readonly accessorName: "ranked_planet" };
    /** @deprecated Use `rankedPlanetReservation` instead. This alias will be removed in the next major version. */
    readonly "ranked_planet_reservation": Omit<typeof tablesSchema.schemaType.tables["rankedPlanetReservation"], "accessorName"> & { readonly accessorName: "ranked_planet_reservation" };
    /** @deprecated Use `rankedSeason` instead. This alias will be removed in the next major version. */
    readonly "ranked_season": Omit<typeof tablesSchema.schemaType.tables["rankedSeason"], "accessorName"> & { readonly accessorName: "ranked_season" };
    /** @deprecated Use `serverClock` instead. This alias will be removed in the next major version. */
    readonly "server_clock": Omit<typeof tablesSchema.schemaType.tables["serverClock"], "accessorName"> & { readonly accessorName: "server_clock" };
    /** @deprecated Use `myCandidate` instead. This alias will be removed in the next major version. */
    readonly "my_candidate": Omit<typeof tablesSchema.schemaType.tables["myCandidate"], "accessorName"> & { readonly accessorName: "my_candidate" };
    /** @deprecated Use `myCandidatePlayers` instead. This alias will be removed in the next major version. */
    readonly "my_candidate_players": Omit<typeof tablesSchema.schemaType.tables["myCandidatePlayers"], "accessorName"> & { readonly accessorName: "my_candidate_players" };
    /** @deprecated Use `myMatchUsage` instead. This alias will be removed in the next major version. */
    readonly "my_match_usage": Omit<typeof tablesSchema.schemaType.tables["myMatchUsage"], "accessorName"> & { readonly accessorName: "my_match_usage" };
    /** @deprecated Use `myQueueEntry` instead. This alias will be removed in the next major version. */
    readonly "my_queue_entry": Omit<typeof tablesSchema.schemaType.tables["myQueueEntry"], "accessorName"> & { readonly accessorName: "my_queue_entry" };
    /** @deprecated Use `rankedTop` instead. This alias will be removed in the next major version. */
    readonly "ranked_top": Omit<typeof tablesSchema.schemaType.tables["rankedTop"], "accessorName"> & { readonly accessorName: "ranked_top" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.1" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "match_entity": "matchEntity",
  "match_event": "matchEvent",
  "match_history": "matchHistory",
  "match_msg": "matchMsg",
  "match_objective": "matchObjective",
  "match_player": "matchPlayer",
  "party_member": "partyMember",
  "planet_control_history": "planetControlHistory",
  "planet_discovery": "planetDiscovery",
  "player_inventory": "playerInventory",
  "player_loadout": "playerLoadout",
  "player_presence": "playerPresence",
  "player_settings": "playerSettings",
  "player_stats": "playerStats",
  "player_wallet": "playerWallet",
  "profile_view": "profileView",
  "rank_history": "rankHistory",
  "ranked_location_discovery": "rankedLocationDiscovery",
  "ranked_planet": "rankedPlanet",
  "ranked_planet_reservation": "rankedPlanetReservation",
  "ranked_season": "rankedSeason",
  "server_clock": "serverClock",
  "my_candidate": "myCandidate",
  "my_candidate_players": "myCandidatePlayers",
  "my_match_usage": "myMatchUsage",
  "my_queue_entry": "myQueueEntry",
  "ranked_top": "rankedTop",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `matchEntity` instead. This alias will be removed in the next major version. */
  readonly "match_entity": __DbViewBase["matchEntity"];
  /** @deprecated Use `matchEvent` instead. This alias will be removed in the next major version. */
  readonly "match_event": __DbViewBase["matchEvent"];
  /** @deprecated Use `matchHistory` instead. This alias will be removed in the next major version. */
  readonly "match_history": __DbViewBase["matchHistory"];
  /** @deprecated Use `matchMsg` instead. This alias will be removed in the next major version. */
  readonly "match_msg": __DbViewBase["matchMsg"];
  /** @deprecated Use `matchObjective` instead. This alias will be removed in the next major version. */
  readonly "match_objective": __DbViewBase["matchObjective"];
  /** @deprecated Use `matchPlayer` instead. This alias will be removed in the next major version. */
  readonly "match_player": __DbViewBase["matchPlayer"];
  /** @deprecated Use `partyMember` instead. This alias will be removed in the next major version. */
  readonly "party_member": __DbViewBase["partyMember"];
  /** @deprecated Use `planetControlHistory` instead. This alias will be removed in the next major version. */
  readonly "planet_control_history": __DbViewBase["planetControlHistory"];
  /** @deprecated Use `planetDiscovery` instead. This alias will be removed in the next major version. */
  readonly "planet_discovery": __DbViewBase["planetDiscovery"];
  /** @deprecated Use `playerInventory` instead. This alias will be removed in the next major version. */
  readonly "player_inventory": __DbViewBase["playerInventory"];
  /** @deprecated Use `playerLoadout` instead. This alias will be removed in the next major version. */
  readonly "player_loadout": __DbViewBase["playerLoadout"];
  /** @deprecated Use `playerPresence` instead. This alias will be removed in the next major version. */
  readonly "player_presence": __DbViewBase["playerPresence"];
  /** @deprecated Use `playerSettings` instead. This alias will be removed in the next major version. */
  readonly "player_settings": __DbViewBase["playerSettings"];
  /** @deprecated Use `playerStats` instead. This alias will be removed in the next major version. */
  readonly "player_stats": __DbViewBase["playerStats"];
  /** @deprecated Use `playerWallet` instead. This alias will be removed in the next major version. */
  readonly "player_wallet": __DbViewBase["playerWallet"];
  /** @deprecated Use `profileView` instead. This alias will be removed in the next major version. */
  readonly "profile_view": __DbViewBase["profileView"];
  /** @deprecated Use `rankHistory` instead. This alias will be removed in the next major version. */
  readonly "rank_history": __DbViewBase["rankHistory"];
  /** @deprecated Use `rankedLocationDiscovery` instead. This alias will be removed in the next major version. */
  readonly "ranked_location_discovery": __DbViewBase["rankedLocationDiscovery"];
  /** @deprecated Use `rankedPlanet` instead. This alias will be removed in the next major version. */
  readonly "ranked_planet": __DbViewBase["rankedPlanet"];
  /** @deprecated Use `rankedPlanetReservation` instead. This alias will be removed in the next major version. */
  readonly "ranked_planet_reservation": __DbViewBase["rankedPlanetReservation"];
  /** @deprecated Use `rankedSeason` instead. This alias will be removed in the next major version. */
  readonly "ranked_season": __DbViewBase["rankedSeason"];
  /** @deprecated Use `serverClock` instead. This alias will be removed in the next major version. */
  readonly "server_clock": __DbViewBase["serverClock"];
  /** @deprecated Use `myCandidate` instead. This alias will be removed in the next major version. */
  readonly "my_candidate": __DbViewBase["myCandidate"];
  /** @deprecated Use `myCandidatePlayers` instead. This alias will be removed in the next major version. */
  readonly "my_candidate_players": __DbViewBase["myCandidatePlayers"];
  /** @deprecated Use `myMatchUsage` instead. This alias will be removed in the next major version. */
  readonly "my_match_usage": __DbViewBase["myMatchUsage"];
  /** @deprecated Use `myQueueEntry` instead. This alias will be removed in the next major version. */
  readonly "my_queue_entry": __DbViewBase["myQueueEntry"];
  /** @deprecated Use `rankedTop` instead. This alias will be removed in the next major version. */
  readonly "ranked_top": __DbViewBase["rankedTop"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `matchEntity` instead. This alias will be removed in the next major version. */
  readonly "match_entity": __TablesBase["matchEntity"];
  /** @deprecated Use `matchEvent` instead. This alias will be removed in the next major version. */
  readonly "match_event": __TablesBase["matchEvent"];
  /** @deprecated Use `matchHistory` instead. This alias will be removed in the next major version. */
  readonly "match_history": __TablesBase["matchHistory"];
  /** @deprecated Use `matchMsg` instead. This alias will be removed in the next major version. */
  readonly "match_msg": __TablesBase["matchMsg"];
  /** @deprecated Use `matchObjective` instead. This alias will be removed in the next major version. */
  readonly "match_objective": __TablesBase["matchObjective"];
  /** @deprecated Use `matchPlayer` instead. This alias will be removed in the next major version. */
  readonly "match_player": __TablesBase["matchPlayer"];
  /** @deprecated Use `partyMember` instead. This alias will be removed in the next major version. */
  readonly "party_member": __TablesBase["partyMember"];
  /** @deprecated Use `planetControlHistory` instead. This alias will be removed in the next major version. */
  readonly "planet_control_history": __TablesBase["planetControlHistory"];
  /** @deprecated Use `planetDiscovery` instead. This alias will be removed in the next major version. */
  readonly "planet_discovery": __TablesBase["planetDiscovery"];
  /** @deprecated Use `playerInventory` instead. This alias will be removed in the next major version. */
  readonly "player_inventory": __TablesBase["playerInventory"];
  /** @deprecated Use `playerLoadout` instead. This alias will be removed in the next major version. */
  readonly "player_loadout": __TablesBase["playerLoadout"];
  /** @deprecated Use `playerPresence` instead. This alias will be removed in the next major version. */
  readonly "player_presence": __TablesBase["playerPresence"];
  /** @deprecated Use `playerSettings` instead. This alias will be removed in the next major version. */
  readonly "player_settings": __TablesBase["playerSettings"];
  /** @deprecated Use `playerStats` instead. This alias will be removed in the next major version. */
  readonly "player_stats": __TablesBase["playerStats"];
  /** @deprecated Use `playerWallet` instead. This alias will be removed in the next major version. */
  readonly "player_wallet": __TablesBase["playerWallet"];
  /** @deprecated Use `profileView` instead. This alias will be removed in the next major version. */
  readonly "profile_view": __TablesBase["profileView"];
  /** @deprecated Use `rankHistory` instead. This alias will be removed in the next major version. */
  readonly "rank_history": __TablesBase["rankHistory"];
  /** @deprecated Use `rankedLocationDiscovery` instead. This alias will be removed in the next major version. */
  readonly "ranked_location_discovery": __TablesBase["rankedLocationDiscovery"];
  /** @deprecated Use `rankedPlanet` instead. This alias will be removed in the next major version. */
  readonly "ranked_planet": __TablesBase["rankedPlanet"];
  /** @deprecated Use `rankedPlanetReservation` instead. This alias will be removed in the next major version. */
  readonly "ranked_planet_reservation": __TablesBase["rankedPlanetReservation"];
  /** @deprecated Use `rankedSeason` instead. This alias will be removed in the next major version. */
  readonly "ranked_season": __TablesBase["rankedSeason"];
  /** @deprecated Use `serverClock` instead. This alias will be removed in the next major version. */
  readonly "server_clock": __TablesBase["serverClock"];
  /** @deprecated Use `myCandidate` instead. This alias will be removed in the next major version. */
  readonly "my_candidate": __TablesBase["myCandidate"];
  /** @deprecated Use `myCandidatePlayers` instead. This alias will be removed in the next major version. */
  readonly "my_candidate_players": __TablesBase["myCandidatePlayers"];
  /** @deprecated Use `myMatchUsage` instead. This alias will be removed in the next major version. */
  readonly "my_match_usage": __TablesBase["myMatchUsage"];
  /** @deprecated Use `myQueueEntry` instead. This alias will be removed in the next major version. */
  readonly "my_queue_entry": __TablesBase["myQueueEntry"];
  /** @deprecated Use `rankedTop` instead. This alias will be removed in the next major version. */
  readonly "ranked_top": __TablesBase["rankedTop"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

