// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  matchId: __t.u32().name("match_id"),
  entityId: __t.u32().name("entity_id"),
  entityType: __t.u32().name("entity_type"),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  vx: __t.f64(),
  vy: __t.f64(),
  vz: __t.f64(),
  hp: __t.f64(),
  state: __t.u32(),
  target: __t.u32(),
  updatedAt: __t.timestamp().name("updated_at"),
});
