// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  matchId: __t.u32().name("match_id"),
  identity: __t.identity(),
  name: __t.string(),
  colony: __t.u8(),
  kills: __t.u32(),
  deaths: __t.u32(),
  damage: __t.f64(),
  objectives: __t.u32(),
  necrotech: __t.u32(),
  confirmed: __t.bool(),
  connected: __t.bool(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  fx: __t.f64(),
  fy: __t.f64(),
  fz: __t.f64(),
  vx: __t.f64(),
  vy: __t.f64(),
  vz: __t.f64(),
  hp: __t.f64(),
  maxHp: __t.f64().name("max_hp"),
  alive: __t.bool(),
  hasPose: __t.bool().name("has_pose"),
  statsReportedAt: __t.u64().name("stats_reported_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
