// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  matchId: __t.u32().name("match_id"),
  objectiveId: __t.u32().name("objective_id"),
  ownerColony: __t.u8().name("owner_colony"),
  captureProgress: __t.f64().name("capture_progress"),
  shield: __t.u32(),
  state: __t.u32(),
  updatedAt: __t.timestamp().name("updated_at"),
});
