// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.u32().primaryKey().name("match_id"),
  status: __t.u8(),
  createdAt: __t.timestamp().name("created_at"),
  startedAt: __t.option(__t.timestamp()).name("started_at"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
  mapSeed: __t.u32().name("map_seed"),
  winnerColony: __t.option(__t.u8()).name("winner_colony"),
  durationSeconds: __t.u32().name("duration_seconds"),
  serverTick: __t.u64().name("server_tick"),
  playerCount: __t.u32().name("player_count"),
  emptySince: __t.option(__t.timestamp()).name("empty_since"),
  ranked: __t.bool(),
  planetKey: __t.string().name("planet_key"),
  rankRing: __t.u8().name("rank_ring"),
  mode: __t.u8(),
  roomCode: __t.string().name("room_code"),
  hostHex: __t.string().name("host_hex"),
});
