// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  identity: __t.identity(),
  matchId: __t.u32().name("match_id"),
  colony: __t.u8(),
  won: __t.bool(),
  kills: __t.u32(),
  deaths: __t.u32(),
  objectives: __t.u32(),
  durationSeconds: __t.u32().name("duration_seconds"),
  endedAt: __t.timestamp().name("ended_at"),
  softCurrencyEarned: __t.u64().name("soft_currency_earned"),
  xpEarned: __t.u32().name("xp_earned"),
});
