// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.u32().primaryKey().name("match_id"),
  startedAt: __t.option(__t.timestamp()).name("started_at"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
  durationSeconds: __t.u32().name("duration_seconds"),
  playerCount: __t.u32().name("player_count"),
  serverTicks: __t.u64().name("server_ticks"),
  inputCommands: __t.u64().name("input_commands"),
  stateUpdates: __t.u64().name("state_updates"),
  events: __t.u64(),
  estimatedEgressBytes: __t.u64().name("estimated_egress_bytes"),
  storageBytes: __t.u64().name("storage_bytes"),
});
