// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  partyId: __t.option(__t.u32()).name("party_id"),
  colony: __t.u8(),
  skillRating: __t.u32().name("skill_rating"),
  queuedAt: __t.u64().name("queued_at"),
  status: __t.u8(),
  candidateMatchId: __t.option(__t.u32()).name("candidate_match_id"),
});
