// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  planetKey: __t.string().name("planet_key"),
  mode: __t.u8(),
  timeMs: __t.u64().name("time_ms"),
  playerName: __t.string().name("player_name"),
  identity: __t.identity(),
  setAt: __t.timestamp().name("set_at"),
});
