// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  playerName: __t.string().name("player_name"),
  normalizedName: __t.string().name("normalized_name"),
  profileName: __t.string().name("profile_name"),
  profilePicture: __t.u32().name("profile_picture"),
  avatarId: __t.u32().name("avatar_id"),
  colony: __t.u8(),
  level: __t.u32(),
  xp: __t.u64(),
  wins: __t.u32(),
  losses: __t.u32(),
  matchesPlayed: __t.u32().name("matches_played"),
  currentRank: __t.u32().name("current_rank"),
  rankPoints: __t.i32().name("rank_points"),
  rankStatus: __t.u8().name("rank_status"),
  seasonId: __t.u32().name("season_id"),
  skillRating: __t.u32().name("skill_rating"),
  likesReceived: __t.u32().name("likes_received"),
  profileViews: __t.u32().name("profile_views"),
  followersCount: __t.u32().name("followers_count"),
  followingCount: __t.u32().name("following_count"),
  createdAt: __t.timestamp().name("created_at"),
  lastSeenAt: __t.timestamp().name("last_seen_at"),
  lastOnlineAt: __t.timestamp().name("last_online_at"),
  banned: __t.bool(),
  playerCode: __t.string().name("player_code"),
  bio: __t.string(),
  gender: __t.u8(),
  peakRankPoints: __t.i32().name("peak_rank_points"),
});
