// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  kills: __t.u32(),
  deaths: __t.u32(),
  bossKills: __t.u32().name("boss_kills"),
  beaconsCaptured: __t.u32().name("beacons_captured"),
  nexusCaptures: __t.u32().name("nexus_captures"),
  damageDealt: __t.f64().name("damage_dealt"),
  damageTaken: __t.f64().name("damage_taken"),
  playTimeSeconds: __t.u64().name("play_time_seconds"),
  p2PMatches: __t.u32().name("p_2_p_matches"),
  p2PWins: __t.u32().name("p_2_p_wins"),
});
