// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  planetKey: __t.string().primaryKey().name("planet_key"),
  seasonId: __t.u32().name("season_id"),
  ring: __t.u8(),
  galaxyId: __t.u32().name("galaxy_id"),
  systemId: __t.u32().name("system_id"),
  planetId: __t.u32().name("planet_id"),
  seed: __t.u64(),
  state: __t.u8(),
  controllingColony: __t.u8().name("controlling_colony"),
  controlStartedAt: __t.u64().name("control_started_at"),
  controlExpiresAt: __t.u64().name("control_expires_at"),
  discovered: __t.bool(),
  firstDiscoveredAt: __t.u64().name("first_discovered_at"),
  lastMatchId: __t.u32().name("last_match_id"),
  generatedRank: __t.u32().name("generated_rank"),
});
