// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  identity: __t.identity(),
  seasonId: __t.u32().name("season_id"),
  oldTier: __t.u8().name("old_tier"),
  oldDivision: __t.u8().name("old_division"),
  oldStars: __t.u32().name("old_stars"),
  newTier: __t.u8().name("new_tier"),
  newDivision: __t.u8().name("new_division"),
  newStars: __t.u32().name("new_stars"),
  cause: __t.u8(),
  matchId: __t.u32().name("match_id"),
  planetKey: __t.string().name("planet_key"),
  delta: __t.i32(),
  createdAt: __t.timestamp().name("created_at"),
});
