// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  locationKey: __t.string().name("location_key"),
  locationType: __t.u8().name("location_type"),
  ring: __t.u8(),
  galaxyId: __t.u32().name("galaxy_id"),
  systemId: __t.u32().name("system_id"),
  planetId: __t.u32().name("planet_id"),
  playerIdentity: __t.identity().name("player_identity"),
  playerName: __t.string().name("player_name"),
  colony: __t.u8(),
  discoveredAt: __t.u64().name("discovered_at"),
  discoveryIndex: __t.u8().name("discovery_index"),
});
