// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  planetKey: __t.string().primaryKey().name("planet_key"),
  matchId: __t.u32().name("match_id"),
  reservedAt: __t.u64().name("reserved_at"),
  expiresAt: __t.u64().name("expires_at"),
});
