// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  seasonId: __t.u32().primaryKey().name("season_id"),
  universeSeed: __t.u64().name("universe_seed"),
  startedAt: __t.timestamp().name("started_at"),
  endsAt: __t.option(__t.timestamp()).name("ends_at"),
  active: __t.bool(),
  universeGenerationVersion: __t.u32().name("universe_generation_version"),
});
