// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  moveX: __t.f64(),
  moveY: __t.f64(),
  moveZ: __t.f64(),
  aimX: __t.f64(),
  aimY: __t.f64(),
  aimZ: __t.f64(),
  seq: __t.u64(),
  dash: __t.bool(),
};
