// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AdminIdentity = __t.object("AdminIdentity", {
  identity: __t.identity(),
});
export type AdminIdentity = __Infer<typeof AdminIdentity>;

export const CandidateMatch = __t.object("CandidateMatch", {
  matchId: __t.u32(),
  createdAt: __t.u64(),
  deadline: __t.u64(),
  status: __t.u8(),
  ranked: __t.bool(),
  planetKey: __t.string(),
});
export type CandidateMatch = __Infer<typeof CandidateMatch>;

export const ColonyStats = __t.object("ColonyStats", {
  colony: __t.u8(),
  planets: __t.u32(),
  systems: __t.u32(),
  expiring: __t.u32(),
});
export type ColonyStats = __Infer<typeof ColonyStats>;

export const ColonyStatsResult = __t.object("ColonyStatsResult", {
  totalPlanets: __t.u32(),
  totalSystems: __t.u32(),
  get colonies() {
    return __t.array(ColonyStats);
  },
});
export type ColonyStatsResult = __Infer<typeof ColonyStatsResult>;

export const Follow = __t.object("Follow", {
  id: __t.u32(),
  follower: __t.identity(),
  following: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Follow = __Infer<typeof Follow>;

export const Match = __t.object("Match", {
  matchId: __t.u32(),
  status: __t.u8(),
  createdAt: __t.timestamp(),
  startedAt: __t.option(__t.timestamp()),
  endedAt: __t.option(__t.timestamp()),
  mapSeed: __t.u32(),
  winnerColony: __t.option(__t.u8()),
  durationSeconds: __t.u32(),
  serverTick: __t.u64(),
  playerCount: __t.u32(),
  emptySince: __t.option(__t.timestamp()),
  ranked: __t.bool(),
  planetKey: __t.string(),
  rankRing: __t.u8(),
});
export type Match = __Infer<typeof Match>;

export const MatchCandidatePlayer = __t.object("MatchCandidatePlayer", {
  id: __t.u32(),
  matchId: __t.u32(),
  identity: __t.identity(),
  colony: __t.u8(),
  confirmed: __t.bool(),
  confirmedAt: __t.option(__t.u64()),
});
export type MatchCandidatePlayer = __Infer<typeof MatchCandidatePlayer>;

export const MatchEntity = __t.object("MatchEntity", {
  id: __t.u32(),
  matchId: __t.u32(),
  entityId: __t.u32(),
  entityType: __t.u32(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  vx: __t.f64(),
  vy: __t.f64(),
  vz: __t.f64(),
  hp: __t.f64(),
  state: __t.u32(),
  target: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type MatchEntity = __Infer<typeof MatchEntity>;

export const MatchEvent = __t.object("MatchEvent", {
  id: __t.u32(),
  matchId: __t.u32(),
  kind: __t.u32(),
  a: __t.u32(),
  b: __t.u32(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  at: __t.timestamp(),
});
export type MatchEvent = __Infer<typeof MatchEvent>;

export const MatchHistory = __t.object("MatchHistory", {
  id: __t.u32(),
  identity: __t.identity(),
  matchId: __t.u32(),
  colony: __t.u8(),
  won: __t.bool(),
  kills: __t.u32(),
  deaths: __t.u32(),
  objectives: __t.u32(),
  durationSeconds: __t.u32(),
  endedAt: __t.timestamp(),
  softCurrencyEarned: __t.u64(),
  xpEarned: __t.u32(),
});
export type MatchHistory = __Infer<typeof MatchHistory>;

export const MatchInput = __t.object("MatchInput", {
  id: __t.u32(),
  matchId: __t.u32(),
  identity: __t.identity(),
  moveX: __t.f64(),
  moveY: __t.f64(),
  moveZ: __t.f64(),
  aimX: __t.f64(),
  aimY: __t.f64(),
  aimZ: __t.f64(),
  seq: __t.u64(),
  dashSeq: __t.u64(),
  poseX: __t.f64(),
  poseY: __t.f64(),
  poseZ: __t.f64(),
  poseFx: __t.f64(),
  poseFy: __t.f64(),
  poseFz: __t.f64(),
  lastInputAt: __t.u64(),
  lastPoseAt: __t.u64(),
});
export type MatchInput = __Infer<typeof MatchInput>;

export const MatchObjective = __t.object("MatchObjective", {
  id: __t.u32(),
  matchId: __t.u32(),
  objectiveId: __t.u32(),
  ownerColony: __t.u8(),
  captureProgress: __t.f64(),
  shield: __t.u32(),
  state: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type MatchObjective = __Infer<typeof MatchObjective>;

export const MatchPlayer = __t.object("MatchPlayer", {
  id: __t.u32(),
  matchId: __t.u32(),
  identity: __t.identity(),
  name: __t.string(),
  colony: __t.u8(),
  kills: __t.u32(),
  deaths: __t.u32(),
  damage: __t.f64(),
  objectives: __t.u32(),
  necrotech: __t.u32(),
  confirmed: __t.bool(),
  connected: __t.bool(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  fx: __t.f64(),
  fy: __t.f64(),
  fz: __t.f64(),
  vx: __t.f64(),
  vy: __t.f64(),
  vz: __t.f64(),
  hp: __t.f64(),
  maxHp: __t.f64(),
  alive: __t.bool(),
  hasPose: __t.bool(),
  statsReportedAt: __t.u64(),
  updatedAt: __t.timestamp(),
  left: __t.bool(),
});
export type MatchPlayer = __Infer<typeof MatchPlayer>;

export const MatchServerUsage = __t.object("MatchServerUsage", {
  matchId: __t.u32(),
  startedAt: __t.option(__t.timestamp()),
  endedAt: __t.option(__t.timestamp()),
  durationSeconds: __t.u32(),
  playerCount: __t.u32(),
  serverTicks: __t.u64(),
  inputCommands: __t.u64(),
  stateUpdates: __t.u64(),
  events: __t.u64(),
  estimatedEgressBytes: __t.u64(),
  storageBytes: __t.u64(),
});
export type MatchServerUsage = __Infer<typeof MatchServerUsage>;

export const MatchTick = __t.object("MatchTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  matchId: __t.u32(),
});
export type MatchTick = __Infer<typeof MatchTick>;

export const MatchmakingScan = __t.object("MatchmakingScan", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MatchmakingScan = __Infer<typeof MatchmakingScan>;

export const MyCandidate = __t.object("MyCandidate", {});
export type MyCandidate = __Infer<typeof MyCandidate>;

export const MyCandidatePlayers = __t.object("MyCandidatePlayers", {});
export type MyCandidatePlayers = __Infer<typeof MyCandidatePlayers>;

export const MyMatchUsage = __t.object("MyMatchUsage", {});
export type MyMatchUsage = __Infer<typeof MyMatchUsage>;

export const MyQueueEntry = __t.object("MyQueueEntry", {});
export type MyQueueEntry = __Infer<typeof MyQueueEntry>;

export const Party = __t.object("Party", {
  partyId: __t.u32(),
  leader: __t.identity(),
  state: __t.u8(),
  createdAt: __t.timestamp(),
  joinCode: __t.string(),
});
export type Party = __Infer<typeof Party>;

export const PartyMember = __t.object("PartyMember", {
  id: __t.u32(),
  partyId: __t.u32(),
  identity: __t.identity(),
  joinedAt: __t.timestamp(),
  acc: __t.string(),
});
export type PartyMember = __Infer<typeof PartyMember>;

export const PlanetControlHistory = __t.object("PlanetControlHistory", {
  id: __t.u32(),
  planetKey: __t.string(),
  colony: __t.u8(),
  matchId: __t.u32(),
  startedAt: __t.u64(),
  endedAt: __t.u64(),
});
export type PlanetControlHistory = __Infer<typeof PlanetControlHistory>;

export const PlanetDiscovery = __t.object("PlanetDiscovery", {
  id: __t.u32(),
  planetKey: __t.string(),
  identity: __t.identity(),
  playerName: __t.string(),
  discoveredAt: __t.u64(),
  discoveryOrder: __t.u8(),
});
export type PlanetDiscovery = __Infer<typeof PlanetDiscovery>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  playerName: __t.string(),
  normalizedName: __t.string(),
  profileName: __t.string(),
  profilePicture: __t.u32(),
  avatarId: __t.u32(),
  colony: __t.u8(),
  level: __t.u32(),
  xp: __t.u64(),
  wins: __t.u32(),
  losses: __t.u32(),
  matchesPlayed: __t.u32(),
  currentRank: __t.u32(),
  rankPoints: __t.i32(),
  rankStatus: __t.u8(),
  seasonId: __t.u32(),
  skillRating: __t.u32(),
  likesReceived: __t.u32(),
  profileViews: __t.u32(),
  followersCount: __t.u32(),
  followingCount: __t.u32(),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
  lastOnlineAt: __t.timestamp(),
  banned: __t.bool(),
  playerCode: __t.string(),
});
export type Player = __Infer<typeof Player>;

export const PlayerInventory = __t.object("PlayerInventory", {
  id: __t.u32(),
  identity: __t.identity(),
  itemId: __t.u32(),
  quantity: __t.u32(),
  acquiredAt: __t.timestamp(),
});
export type PlayerInventory = __Infer<typeof PlayerInventory>;

export const PlayerLoadout = __t.object("PlayerLoadout", {
  id: __t.u32(),
  identity: __t.identity(),
  slot: __t.u32(),
  itemId: __t.u32(),
});
export type PlayerLoadout = __Infer<typeof PlayerLoadout>;

export const PlayerPresence = __t.object("PlayerPresence", {
  identity: __t.identity(),
  status: __t.u8(),
  lastSeen: __t.timestamp(),
});
export type PlayerPresence = __Infer<typeof PlayerPresence>;

export const PlayerSearchHit = __t.object("PlayerSearchHit", {
  identity: __t.identity(),
  playerName: __t.string(),
  playerCode: __t.string(),
  colony: __t.u8(),
  level: __t.u32(),
});
export type PlayerSearchHit = __Infer<typeof PlayerSearchHit>;

export const PlayerSettings = __t.object("PlayerSettings", {
  identity: __t.identity(),
  keybinds: __t.string(),
});
export type PlayerSettings = __Infer<typeof PlayerSettings>;

export const PlayerStats = __t.object("PlayerStats", {
  identity: __t.identity(),
  kills: __t.u32(),
  deaths: __t.u32(),
  bossKills: __t.u32(),
  beaconsCaptured: __t.u32(),
  nexusCaptures: __t.u32(),
  damageDealt: __t.f64(),
  damageTaken: __t.f64(),
  playTimeSeconds: __t.u64(),
  p2PMatches: __t.u32(),
  p2PWins: __t.u32(),
});
export type PlayerStats = __Infer<typeof PlayerStats>;

export const PlayerWallet = __t.object("PlayerWallet", {
  identity: __t.identity(),
  softCurrency: __t.u64(),
  premiumCurrency: __t.u64(),
});
export type PlayerWallet = __Infer<typeof PlayerWallet>;

export const ProfileView = __t.object("ProfileView", {
  id: __t.u32(),
  viewer: __t.identity(),
  profile: __t.identity(),
  lastViewedAt: __t.timestamp(),
  viewCount: __t.u32(),
});
export type ProfileView = __Infer<typeof ProfileView>;

export const QueueEntry = __t.object("QueueEntry", {
  identity: __t.identity(),
  partyId: __t.option(__t.u32()),
  colony: __t.u8(),
  skillRating: __t.u32(),
  queuedAt: __t.u64(),
  status: __t.u8(),
  candidateMatchId: __t.option(__t.u32()),
  ranked: __t.bool(),
  planetKey: __t.string(),
});
export type QueueEntry = __Infer<typeof QueueEntry>;

export const RankHistory = __t.object("RankHistory", {
  id: __t.u32(),
  identity: __t.identity(),
  seasonId: __t.u32(),
  oldTier: __t.u8(),
  oldDivision: __t.u8(),
  oldStars: __t.u32(),
  newTier: __t.u8(),
  newDivision: __t.u8(),
  newStars: __t.u32(),
  cause: __t.u8(),
  matchId: __t.u32(),
  planetKey: __t.string(),
  delta: __t.i32(),
  createdAt: __t.timestamp(),
});
export type RankHistory = __Infer<typeof RankHistory>;

export const RankedPlanet = __t.object("RankedPlanet", {
  planetKey: __t.string(),
  seasonId: __t.u32(),
  ring: __t.u8(),
  galaxyId: __t.u32(),
  systemId: __t.u32(),
  planetId: __t.u32(),
  seed: __t.u64(),
  state: __t.u8(),
  controllingColony: __t.u8(),
  controlStartedAt: __t.u64(),
  controlExpiresAt: __t.u64(),
  discovered: __t.bool(),
  firstDiscoveredAt: __t.u64(),
  lastMatchId: __t.u32(),
  generatedRank: __t.u32(),
});
export type RankedPlanet = __Infer<typeof RankedPlanet>;

export const RankedPlanetReservation = __t.object("RankedPlanetReservation", {
  planetKey: __t.string(),
  matchId: __t.u32(),
  reservedAt: __t.u64(),
  expiresAt: __t.u64(),
});
export type RankedPlanetReservation = __Infer<typeof RankedPlanetReservation>;

export const RankedSeason = __t.object("RankedSeason", {
  seasonId: __t.u32(),
  universeSeed: __t.u64(),
  startedAt: __t.timestamp(),
  endsAt: __t.option(__t.timestamp()),
  active: __t.bool(),
});
export type RankedSeason = __Infer<typeof RankedSeason>;

export const RankedTop = __t.object("RankedTop", {});
export type RankedTop = __Infer<typeof RankedTop>;

