// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as SearchPlayersProcedure from "../search_players_procedure";

export type SearchPlayersArgs = __Infer<typeof SearchPlayersProcedure.params>;
export type SearchPlayersResult = __Infer<typeof SearchPlayersProcedure.returnType>;

