// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CancelFindMatchReducer from "../cancel_find_match_reducer";
import ChooseColonyReducer from "../choose_colony_reducer";
import ClaimAdminReducer from "../claim_admin_reducer";
import ConfirmMatchReducer from "../confirm_match_reducer";
import CreatePartyReducer from "../create_party_reducer";
import DeclineMatchReducer from "../decline_match_reducer";
import EquipItemReducer from "../equip_item_reducer";
import FindMatchReducer from "../find_match_reducer";
import FollowPlayerReducer from "../follow_player_reducer";
import GrantCurrencyAdminReducer from "../grant_currency_admin_reducer";
import GrantItemAdminReducer from "../grant_item_admin_reducer";
import JoinMatchReducer from "../join_match_reducer";
import JoinPartyReducer from "../join_party_reducer";
import JoinPartyByCodeReducer from "../join_party_by_code_reducer";
import KickFromPartyReducer from "../kick_from_party_reducer";
import LeaveMatchReducer from "../leave_match_reducer";
import LeavePartyReducer from "../leave_party_reducer";
import RecordProfileViewReducer from "../record_profile_view_reducer";
import ReportMatchStatsReducer from "../report_match_stats_reducer";
import SetAvatarReducer from "../set_avatar_reducer";
import SetBanAdminReducer from "../set_ban_admin_reducer";
import SetKeybindsReducer from "../set_keybinds_reducer";
import SetPartyLoadoutReducer from "../set_party_loadout_reducer";
import SetPlayerNameReducer from "../set_player_name_reducer";
import SetProfileNameReducer from "../set_profile_name_reducer";
import SetProfilePictureReducer from "../set_profile_picture_reducer";
import SubmitInputReducer from "../submit_input_reducer";
import SubmitPeerResultReducer from "../submit_peer_result_reducer";
import SyncPoseReducer from "../sync_pose_reducer";
import UnfollowPlayerReducer from "../unfollow_player_reducer";

export type CancelFindMatchParams = __Infer<typeof CancelFindMatchReducer>;
export type ChooseColonyParams = __Infer<typeof ChooseColonyReducer>;
export type ClaimAdminParams = __Infer<typeof ClaimAdminReducer>;
export type ConfirmMatchParams = __Infer<typeof ConfirmMatchReducer>;
export type CreatePartyParams = __Infer<typeof CreatePartyReducer>;
export type DeclineMatchParams = __Infer<typeof DeclineMatchReducer>;
export type EquipItemParams = __Infer<typeof EquipItemReducer>;
export type FindMatchParams = __Infer<typeof FindMatchReducer>;
export type FollowPlayerParams = __Infer<typeof FollowPlayerReducer>;
export type GrantCurrencyAdminParams = __Infer<typeof GrantCurrencyAdminReducer>;
export type GrantItemAdminParams = __Infer<typeof GrantItemAdminReducer>;
export type JoinMatchParams = __Infer<typeof JoinMatchReducer>;
export type JoinPartyParams = __Infer<typeof JoinPartyReducer>;
export type JoinPartyByCodeParams = __Infer<typeof JoinPartyByCodeReducer>;
export type KickFromPartyParams = __Infer<typeof KickFromPartyReducer>;
export type LeaveMatchParams = __Infer<typeof LeaveMatchReducer>;
export type LeavePartyParams = __Infer<typeof LeavePartyReducer>;
export type RecordProfileViewParams = __Infer<typeof RecordProfileViewReducer>;
export type ReportMatchStatsParams = __Infer<typeof ReportMatchStatsReducer>;
export type SetAvatarParams = __Infer<typeof SetAvatarReducer>;
export type SetBanAdminParams = __Infer<typeof SetBanAdminReducer>;
export type SetKeybindsParams = __Infer<typeof SetKeybindsReducer>;
export type SetPartyLoadoutParams = __Infer<typeof SetPartyLoadoutReducer>;
export type SetPlayerNameParams = __Infer<typeof SetPlayerNameReducer>;
export type SetProfileNameParams = __Infer<typeof SetProfileNameReducer>;
export type SetProfilePictureParams = __Infer<typeof SetProfilePictureReducer>;
export type SubmitInputParams = __Infer<typeof SubmitInputReducer>;
export type SubmitPeerResultParams = __Infer<typeof SubmitPeerResultReducer>;
export type SyncPoseParams = __Infer<typeof SyncPoseReducer>;
export type UnfollowPlayerParams = __Infer<typeof UnfollowPlayerReducer>;

